### ISSUE TITLE
是否可以自定义文件夹名/文件名，或者用另外一个命名方式

### ISSUE THREAD

**Issue by maplestory03** [Tsuk1ko/pxder#12]
自定义文件夹名/文件名 用作者ID、作者名、作品ID、作品名等
这种方式灵活度比较高
目前用了不少下载工具模板基本都是[uid]/pid_p0(只有1张图就是p0)
如果还不方便做自定义名称，时候可以考虑另开上述模板供选择设置？

**Comment by Tsuk1ko** [comment]
这个是在计划中的改进

但是命令行程序在展示设置方面会有点拙鸡，因此打算以后（咕咕咕）开发可视化界面的时候再加入这一设置，包括批量自动重命名等

**Comment by maplestory03** [comment]
在咕咕咕之前可以先做个新模板的选择吗（手动滑稽）
1、原命名方式
2、文件夹：[画师ID]、文件名：作品ID_p0(1张的显示0，多张往上），动图压缩包就不要加p0后缀了（如果修改比较麻烦，不改也可以，可以用批量修改工具）

**Comment by Tsuk1ko** [comment]
@maplestory03 目前的命令行程序是不想再动了（摊 _(:3」∠)_
