### ISSUE TITLE
在网络正常的情况下出现network error

### ISSUE THREAD

**Issue by ALICEOFALICE** [Tsuk1ko/pxder#14]
正常设置脚本后运行，必定会卡在一个地方并提示：Network error! Pause 5 minutes.

![TIM截图20190609225930](https://user-images.githubusercontent.com/41146748/59160615-441a0300-8b0a-11e9-89bc-cdd1071b5256.png)
pixiv地址能被ping通过

**Comment by Tsuk1ko** [comment]
能尝试一下执行命令的时候加上`--debug`参数，然后把错误信息截图发一下吗（不用全部截，截一段完整的就行

**Comment by ALICEOFALICE** [comment]
![TIM截图20190609230651](https://user-images.githubusercontent.com/41146748/59160683-50529000-8b0b-11e9-9996-c70ac093ff1a.png)
这样

**Comment by Tsuk1ko** [comment]
请问你是直接下载在本机硬盘还是通过网络挂载的硬盘？

**Comment by ALICEOFALICE** [comment]
阿里云香港服务器。使用的是阿里云提供的硬盘，环境centos7 x86_64

**Comment by Tsuk1ko** [comment]
请尝试更新到最新版本，看看问题是否仍有出现

这个可能跟 Linux 文件系统有关，根据以前的经验尝试修复了下

**Comment by ALICEOFALICE** [comment]
已经解决，感谢。
