### ISSUE TITLE
大佬，菜鸡问一下登录不了咋办。。。。。用的梯子能在网页上P站的

### ISSUE THREAD

**Issue by q972705035** [Tsuk1ko/pxder#15]
C:\Users\Administrator>pxder --login

Pixiv Login

[33mUsername: [39m972705035
[33mPassword: [39m******
Error: connect ETIMEDOUT 66.220.152.28:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '66.220.152.28',
  port: 443,
  config: {
    url: 'https://oauth.secure.pixiv.net/auth/token',
    method: 'post',
    data: 'client_id=KzEZED7aC0vird8jWyHM38mXjNTY&client_secret=W9JZoJe00qPvJsiy
CGT3CCtC6ZUtdpKpzMbNlUGP&get_secure_url=1&grant_type=password&username=972705035
&password=960214',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/x-www-form-urlencoded',
      'User-Agent': 'axios/0.19.0',
      'Content-Length': 165
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      protocol: 'https:',
      maxRedirects: 21,
      maxBodyLength: 10485760,
      path: '/auth/token',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      auth: undefined,
      hostname: 'oauth.secure.pixiv.net',
      port: null,
      nativeProtocols: [Object],
      pathname: '/auth/token'
    },
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 165,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'POST /auth/token HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/x-www-form-urlencoded\r\n' +
        'User-Agent: axios/0.19.0\r\n' +
        'Content-Length: 165\r\n' +
        'Host: oauth.secure.pixiv.net\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      path: '/auth/token',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      _redirectable: [Circular],
      [Symbol(isCorked)]: false,
      [Symbol(outHeadersKey)]: [Object: null prototype]
    },
    _currentUrl: 'https://oauth.secure.pixiv.net/auth/token'
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function]
}

**Comment by Luobogao** [comment]
检查一下是不是输错密码了？

**Comment by Tsuk1ko** [comment]
@q972705035 66.220.152.28 是 Facebook 的 IP，说明仍有DNS污染现象
请检查你是否有在`pxder --setting`中正确设置代理

**Comment by q972705035** [comment]
多谢大佬解答，的确是代理问题，已解决
