### ISSUE TITLE
增量更新是如何判断的？本地文件？还是数据库里有记录?

### ISSUE THREAD

**Issue by Uzibird** [Tsuk1ko/pxder#27]
我想下载下来后再剪切到网盘上，本地文件被删除后 它 下次增量更新会重新下载之前的图片吗?

**Comment by Tsuk1ko** [comment]
只是简单根据文件名判断

- 通常情况  
从 API 拉取画师画作列表每次 30 个，如果这 30 个图都存在则停止拉取并开始下载
- `pxder -f`  
API 返回画师信息会附带其最近 3 张作品，如果这 3 张都存在则跳过该画师，否则开始从 API 拉取画作列表，与“通常情况”一致

**Comment by Uzibird** [comment]
好吧，感谢回答。
 还想着如果是存在数据库里的记录就好了，就可以给服务器上省点空间了。
