### ISSUE TITLE
使用Pid下载指定图片遇到重复项会报错

### ISSUE THREAD

**Issue by Silver-Meow** [Tsuk1ko/pxder#30]
其实我这个角度有点刁钻2333.
事情是这样的，有一天我看到了一个画师的几个作品，想把它们下载下来。
输入几个id以后启动脚本，下到一半的时候我代理出了点问题，就退出去改了一下。
然后回来重新下载的时候还是用的上次的命令行（同一组id），那时候网又不是很好，然后从第一张就开始弹那种黄色的重试，我就一直等呀等呀等…………………………
等了两天以后我打开那个文件夹突然发现之前的图已经下好了呀，然后我才发现是被同样的任务卡住了。
嗯……就是过来留言提示一下，改不改都不要紧的2333，很感谢作者大大的脚本~

顺便请教一下，脚本缓存的动图压缩包用什么查看器会好一点呢~

**Comment by Tsuk1ko** [comment]
对这确实是个 bug，因为当初按 pid 下载这个功能是他人加上 pr 到我这里的，由于使用频率很低所以我自己也没发现有问题😂

总之非常感谢你发现了问题，已经在 v2.7.9 修复

动图的压缩包实际上就是一个所有静态帧的一个压缩包而已，并没有什么专用的查看器，最多只能解压出来一张张翻看而已
