### ISSUE TITLE
下载报错...这个是什么情况呢..

### ISSUE THREAD

**Issue by HanamoriRen** [Tsuk1ko/pxder#31]
![1653f5b0fee727f1a5bd140d9c8a48e4_a2e83fa0af9376bde905746dfb23a717](https://user-images.githubusercontent.com/48375071/74667563-7114ce80-51de-11ea-9335-9eada45211ed.png)

**Comment by Tsuk1ko** [comment]
可以提供一下出错的 UID 吗

**Comment by HanamoriRen** [comment]
705370

**Comment by Tsuk1ko** [comment]
我这没问题来着，你这个情况可能是网络问题导致的

![image](https://user-images.githubusercontent.com/24877906/74669176-9820cf80-51e1-11ea-938d-e6bb4ff9102f.png)

**Comment by HanamoriRen** [comment]
唔...也试过重装后重新设置了...还是不可以...

**Comment by Tsuk1ko** [comment]
你是有在使用代理的是么

**Comment by HanamoriRen** [comment]
嗯,在用小飞机

**Comment by Tsuk1ko** [comment]
如果只有这个画师出错，而且每次都是在同一个进度(Progress: 79)出错的话，那我想到的可能的原因只有 api 返回的内容恰好有什么文字命中了你用的那家机场的某条审计规则，导致被拦截，返回了不正确的内容

你可以尝试找朋友借一下不同商家的代理试试

**Comment by HanamoriRen** [comment]
好像不止这个画师...刚刚换了个画师试了试也是这样...然后Progress也不止79 30 178也出过... 现在不知道出问题在哪里q-q

**Comment by HanamoriRen** [comment]
唔...可能是网络问题...我去找朋友借个代理试试...蟹蟹啦~

**Comment by Tsuk1ko** [comment]
这样，你用下面这个命令装一下测试版，再去下载看看报错的时候的输出，截图发一下

```
npm i -g pxder@test
```

**Comment by HanamoriRen** [comment]
唔...刚刚尝试了一下突然又可以了...不知道发生了什么...可能和前两天机场炸过有关吧...?

**Comment by Tsuk1ko** [comment]
🤣行吧，如果还出现这种情况可以来这里反馈下

**Comment by HanamoriRen** [comment]
好的,蟹蟹~
