### ISSUE TITLE
代理设置无效

### ISSUE THREAD

**Issue by Cardidi** [Tsuk1ko/pxder#33]
![image](https://user-images.githubusercontent.com/26651344/75160124-7af57f00-5754-11ea-9ced-a19b17eaaaec.png)

使用的v2ray，系统已经设置代理，地址是http://127.0.0.1:8888。
可以从浏览器直接访问pixiv，但是使用相同的代理配置却无法使用pxder访问。
尝试给系统设置HOST，但是在使用ipconfig /flushdns后还是不能生效。
（上图是我的配置与尝试登陆的结果）
（我没有在qv2ray上看到有关于pixiv.net的连接日志）

**Comment by Tsuk1ko** [comment]
登录操作确实没有应用代理，以前`oauth.secure.pixiv.net`还没有被污染，因此不需要代理，但现在确实已经开始被污染了

已经在 v2.8.1 修复

**Comment by Cardidi** [comment]
已确认修复，谢谢作者大大😀
