### ISSUE TITLE
增加一个命令行参数用于指定下载目录

### ISSUE THREAD

**Issue by Zynismus16** [Tsuk1ko/pxder#38]
大大，我想问问入果我想同时下载公开及私密画师，是否可以运行
`pxder -fF`
如果不是我应该如何运行呢，谢谢。

**Comment by Tsuk1ko** [comment]
是可以的，就如你所说这样即可

**Comment by Zynismus16** [comment]
顺便问下，运行后很大概率会提示这个，这是因为p站限制了还是我VPS问题啊
`Network error! Pause 5 minutes。`
在此先谢过大大解惑

**Comment by Tsuk1ko** [comment]
加`--debug`参数看下具体错误输出

**Comment by Zynismus16** [comment]
好的，由于我是以定时任务运行，修改指令后执行目前还未再次出现异常，有报告了我会尽快回复，谢谢

**Comment by Zynismus16** [comment]
大大，今天查看运行日志发现了这个，虽然报错后还会继续运行
{ Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1095:19)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 'ECONNRESET',
  path: null,
  host: 'i-cf.pximg.net',
  port: 443,
  localAddress: undefined,
  config:
   { url:
      'https://i-cf.pximg.net/img-original/img/2019/04/20/00/06/40/74280072_p11.jpg',
     method: 'get',
     headers:
      { Accept: 'application/json, text/plain, */*',
        referer: 'https://www.pixiv.net/',
        'User-Agent': 'axios/0.19.2' },
     transformRequest: [ [Function: transformRequest] ],
     transformResponse: [ [Function: transformResponse] ],
     timeout: 30000,
     adapter: [Function: httpAdapter],
     responseType: 'stream',
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',

**Comment by Tsuk1ko** [comment]
你是用了代理吧，`ECONNRESET`是受到 gfw 干扰连接重置的常见现象，程序会自动重试所以没关系

如果是这个错误导致的网络错误暂停 5 分钟，那么可以忽略这个问题，这是正常现象，目的是等待代理程序自动重建连接

**Comment by Zynismus16** [comment]
目前并没出现暂停5分钟了。
另外，大大可否考虑下载关注画师内容时像关注作品那样，区分出公开和私人关注呢。
再次感谢大大提供这么好的项目，望采纳。

**Comment by Tsuk1ko** [comment]
[有的呀](https://github.com/Tsuk1ko/pxder#2-%E4%B8%8B%E8%BD%BD%E6%88%96%E6%9B%B4%E6%96%B0%E4%BD%A0%E5%85%B3%E6%B3%A8%E7%9A%84%E6%89%80%E6%9C%89%E7%94%BB%E5%B8%88%E7%9A%84%E6%89%80%E6%9C%89%E6%8F%92%E7%94%BB%E4%BD%9C%E5%93%81)

**Comment by Zynismus16** [comment]
那个是同时下载命令，我的意思是像公开和私人收藏那样，把下载的画师按公开和私人分两个文件夹。

**Comment by Zynismus16** [comment]
) 下载或更新你的收藏中的插画作品

公开收藏

**插画会被下载至[bookmark] Public文件夹中**


pxder -b
# 或
pxder --bookmark
私密收藏

**插画会被下载至[bookmark] Private文件夹中**

pxder -B
# 或
pxder --bookmark--private

**Comment by Zynismus16** [comment]
下载或更新你的收藏中的插画作品

公开收藏

# 插画会被下载至[bookmark] Public文件夹中

pxder -b
或
pxder --bookmark
私密收藏

# 插画会被下载至[bookmark] Private文件夹中

pxder -B
或
pxder --bookmark--private

**Comment by Tsuk1ko** [comment]
那我只能加多一个参数，可以用来指定下载目录以覆盖原本的设置

**Comment by Zynismus16** [comment]
感谢大佬
