### ISSUE TITLE
Rate limit 

### ISSUE THREAD

**Issue by Silver-Meow** [Tsuk1ko/pxder#39]
抓作者（id：1699041）全部作品 进行到369项的时候出现了这个。

嗯……我猜大概是因为动图太多了？

如果我手动把他的作品一张一张存下来（比如我先定一个小目标，存他个90%的动图），放在相关目录里按规则命名之后，再启动脚本批量去扫图，还会出现这个错误么~

**Comment by Tsuk1ko** [comment]
这是因为以前有人提了获取动图帧的时间信息的需求，所以每张动图都会请求一次 api，然后图太多调用频率超了

我稍后改一下，如果超过多少张就不进行请求，以及加一些参数选项来控制

**Comment by Tsuk1ko** [comment]
已发布 v2.8.6，现在可以通过`-M`参数来禁止获取动图的元数据

至于超过多少张不请求，看了下由于以前写的逻辑改起来不太方便，所以咕了（

**Comment by Silver-Meow** [comment]
感谢大佬~
