### ISSUE TITLE
能不能考虑将关注列表用户所有作品图片链接全部读取并存储后再开始下载？

### ISSUE THREAD

**Issue by Shinaki** [Tsuk1ko/pxder#42]
因为我发现国内pixiv网站虽然被墙，但是图片地址并没有，所以在vpn速度有限、关注用户太多情况下，可以先vpn连接上获取图片链接，然后断开vpn再进行下载，下载速度会好得多

**Comment by Tsuk1ko** [comment]
那我建议直接参考[这篇教程](https://2heng.xin/2017/09/19/pixiv/)使用本地反代绕过 SNI 审查，这样根本就不需要代理

**Comment by Shinaki** [comment]
好的，我去了解一下

**Comment by Shinaki** [comment]
首先谢谢您，上面的问题用链接方法解决了。另外还有2个问题请教一下：     1.请问可以考虑根据时间更新所有用户的插图吗？因为如果今天我下载所有用户插图，但是手动去除了一些不需要的图片，根据目前的更新命令是否会重新下载这部分内容？   2.如何过滤不下载动图及漫画内容？

**Comment by Tsuk1ko** [comment]
1. 会重新下载，目前的机制是，只有当某一页插画全都已下载，才不会继续往后拉取，所有拉取到的插画只要本地缺失就会下载，目前不会考虑改动这一机制，所以你的想法目前做不到
2. 目前没有筛选下载功能，目前不考虑加

**Comment by Shinaki** [comment]
好的，我明白了
