### ISSUE TITLE
使用Nginx 本地代理怎么设置pxder的代理设置

### ISSUE THREAD

**Issue by wzxyisme** [Tsuk1ko/pxder#44]
我使用的是[Pixiv-Nginx](https://github.com/mashirozx/Pixiv-Nginx)代理，浏览器可以正常浏览p站但pxder的代理设置socks://127.0.0.1:80,443，http://127.0.0.1:80,443和不通过代理都设置过了都不行，请问dalao这个该怎么设置？
![image](https://user-images.githubusercontent.com/45878990/82442335-08393d00-9ad2-11ea-8191-f95d5ae3d9fb.png)

**Comment by Tsuk1ko** [comment]
@wzxyisme 这是本地反代，并非正向代理，不需要也不要设置 pxder 的代理

你只需要给必要的域名设置好 hosts 即可

**Comment by wzxyisme** [comment]
> @wzxyisme 这是本地反代，并非正向代理，不需要也不要设置 pxder 的代理
> 
> 你只需要给必要的域名设置好 hosts 即可

#Pixiv Start
127.0.0.1       pixiv.net 
127.0.0.1       www.pixiv.net 
127.0.0.1       ssl.pixiv.net
127.0.0.1       accounts.pixiv.net 
127.0.0.1       touch.pixiv.net
127.0.0.1       oauth.secure.pixiv.net
127.0.0.1       dic.pixiv.net
127.0.0.1       en-dic.pixiv.net 
127.0.0.1       sketch.pixiv.net
127.0.0.1       payment.pixiv.net
127.0.0.1       factory.pixiv.net 
127.0.0.1       comic.pixiv.net  
127.0.0.1       novel.pixiv.net 
127.0.0.1       imgaz.pixiv.net 
127.0.0.1       sensei.pixiv.net
127.0.0.1       fanbox.pixiv.net
127.0.0.1       source.pixiv.net
127.0.0.1       i1.pixiv.net 
127.0.0.1       i2.pixiv.net 
127.0.0.1       i3.pixiv.net 
127.0.0.1       i4.pixiv.net
127.0.0.1       hls1.pixivsketch.net
127.0.0.1       hls2.pixivsketch.net
127.0.0.1       hls3.pixivsketch.net
127.0.0.1       hls4.pixivsketch.net
127.0.0.1       hls5.pixivsketch.net
127.0.0.1       hls6.pixivsketch.net
127.0.0.1       hls7.pixivsketch.net
127.0.0.1       hls8.pixivsketch.net
127.0.0.1       hls9.pixivsketch.net
127.0.0.1       hls10.pixivsketch.net
127.0.0.1       hls11.pixivsketch.net
127.0.0.1       hls12.pixivsketch.net
127.0.0.1       hls13.pixivsketch.net
127.0.0.1       hls14.pixivsketch.net
127.0.0.1       hls15.pixivsketch.net
127.0.0.1       hls16.pixivsketch.net
127.0.0.1       hls17.pixivsketch.net
127.0.0.1       hls18.pixivsketch.net
127.0.0.1       hls19.pixivsketch.net
127.0.0.1       hls20.pixivsketch.net
127.0.0.1       hlsa1.pixivsketch.net
127.0.0.1       hlsa2.pixivsketch.net
127.0.0.1       hlsa3.pixivsketch.net
127.0.0.1       hlsa4.pixivsketch.net
127.0.0.1       hlsa5.pixivsketch.net
127.0.0.1       hlsa6.pixivsketch.net
127.0.0.1       hlsa7.pixivsketch.net
127.0.0.1       hlsa8.pixivsketch.net
127.0.0.1       hlsa10.pixivsketch.net
127.0.0.1       hlsa11.pixivsketch.net
127.0.0.1       hlsa12.pixivsketch.net
127.0.0.1       hlsa13.pixivsketch.net
127.0.0.1       hlsa14.pixivsketch.net
127.0.0.1       hlsa15.pixivsketch.net
127.0.0.1       hlsa16.pixivsketch.net
127.0.0.1       hlsa17.pixivsketch.net
127.0.0.1       hlsa18.pixivsketch.net
127.0.0.1       hlsa19.pixivsketch.net
127.0.0.1       hlsc1.pixivsketch.net
127.0.0.1       hlsc2.pixivsketch.net
127.0.0.1       hlsc3.pixivsketch.net
127.0.0.1       hlsc4.pixivsketch.net
127.0.0.1       hlsc5.pixivsketch.net
127.0.0.1       hlsc6.pixivsketch.net
127.0.0.1       hlse1.pixivsketch.net
127.0.0.1       hlse2.pixivsketch.net
127.0.0.1       hlse3.pixivsketch.net
127.0.0.1       hlse4.pixivsketch.net
127.0.0.1       hlse5.pixivsketch.net
127.0.0.1       hlse6.pixivsketch.net
127.0.0.1       hlse7.pixivsketch.net
127.0.0.1       hlse8.pixivsketch.net
127.0.0.1       hlse9.pixivsketch.net
127.0.0.1       hlst1.pixivsketch.net
127.0.0.1       i.pximg.net
210.140.131.220  app-api.pixiv.net  
13.226.113.16    g-client-proxy.pixiv.net 
210.140.131.159 d.pixiv.org 
210.140.92.140  pixiv.pximg.net  
210.140.92.139  s.pximg.net
210.140.131.246  api.booth.pm
210.140.131.220  myaccount.pixiv.net
#Pixiv End
这些是教程里带的，我也加进hosts了还是莫得法
![image](https://user-images.githubusercontent.com/45878990/82445893-3457bc80-9ad8-11ea-8925-81efe31e52b4.png)

**Comment by Tsuk1ko** [comment]
加个`--debug`参数看一下具体错误

**Comment by wzxyisme** [comment]
使用梯子登陆后显示“unable to verify the first certificate”![image](https://user-images.githubusercontent.com/45878990/82448314-1f7d2800-9adc-11ea-8bcc-6f1c0db525ff.png)
但是作者提供的证书我在 本地计算机-自动和收信人的证书颁发机构都装了一遍的

**Comment by Tsuk1ko** [comment]
我指的是`pxder --login --debug`这样

不过我大致懂了，可能确实是证书信任原因，node 里面直接请求并不会读取计算机里的信认证书

我加个忽略证书的设置吧

**Comment by wzxyisme** [comment]
C:\Users\19253>pxder --login --debug

Pixiv Login

Username: 1925349617@qq.com
Password: **********

Login fail! Please check your input or proxy setting.

unable to verify the first certificate

C:\Users\19253>

嗯，同样的提示

**Comment by Tsuk1ko** [comment]
v2.9.0 增加了一个 Certificate validation 设置项，关闭它即可

**Comment by wzxyisme** [comment]
![image](https://user-images.githubusercontent.com/45878990/82481246-9da2f400-9b07-11ea-9874-f849c1fa5f19.png)
关了还是不行誒

**Comment by Tsuk1ko** [comment]
连接重置的话就应该不是证书问题了，你登录是成功了吧？

你试一下下载命令加上`--no-cf`参数

**Comment by wzxyisme** [comment]
登录可以正常登录，下载加参数上还是不行![image](https://user-images.githubusercontent.com/45878990/82484419-7d296880-9b0c-11ea-9cba-5497e8171434.png)

**Comment by Tsuk1ko** [comment]
加上`--debug`看一下具体报错

**Comment by wzxyisme** [comment]
![image](https://user-images.githubusercontent.com/45878990/82485646-5704c800-9b0e-11ea-9504-c01c8bffb7ce.png)

**Comment by Tsuk1ko** [comment]
emmmm，看来我当初写的时候没给连接重置输出错误信息

🤔不过没理由连接重置啊，浏览器能正常看图，说明到 i.pximg.net 没问题

**Comment by wzxyisme** [comment]
要不dalao用那个本地反代加pxder下几张图片试试，看是不是我网络或者电脑设置有问题

**Comment by Tsuk1ko** [comment]
今晚我试试

**Comment by Tsuk1ko** [comment]
@wzxyisme 破案了，hosts 的问题，IP 估计是旧的，你把下面这个域名的改一下

```
210.140.131.218 app-api.pixiv.net
```

![image](https://user-images.githubusercontent.com/24877906/82584732-7ad81480-9bc7-11ea-9d69-c19cc0a9702f.png)

以后遇到这种情况你可以用一些国外的在线 nslookup 工具查

**Comment by wzxyisme** [comment]
![image](https://user-images.githubusercontent.com/45878990/82604270-a4ecff00-9be6-11ea-9c35-36138621df68.png)
![image](https://user-images.githubusercontent.com/45878990/82604287-a9b1b300-9be6-11ea-85cc-a74844018ebf.png)
还是不行啊dalao😭，我用乌班图虚拟机三个IP都试了都不行，pxder -U直接就不跑了😱

**Comment by Tsuk1ko** [comment]
你这个不还是 220 吗……

**Comment by wzxyisme** [comment]
> 你这个不还是 220 吗……

我223 220 218 都试过了不得行

**Comment by Tsuk1ko** [comment]
……貌似是这个域名也被 SNI 审查了，我之前路由器挂着代理所以没事

你改成直接走本地反代就行

```
127.0.0.1 app-api.pixiv.net
```

**Comment by Tsuk1ko** [comment]
虽然不知道为什么 nginx config 里面没有配 app-api.pixiv.net 相关的但是默认也可以反代，不过保险起见还是自己加上配置比较好

```
upstream app-api-pixiv-net { 
    server 210.140.131.218:443;
    server 210.140.131.223:443;
    server 210.140.131.226:443;
}

server {
    listen 443 ssl;
    server_name app-api.pixiv.net;
    
    ssl_certificate ca/pixiv.net.crt;
    ssl_certificate_key ca/pixiv.net.key;
    
    location / {
        proxy_pass https://app-api-pixiv-net;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real_IP $remote_addr;
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header Accept-Encoding ''; 
        proxy_buffering off;
    }
}
```

**Comment by wzxyisme** [comment]
终于成功了，谢谢dalao😘

**Comment by blackhole30** [comment]
大佬您好，我修改了127.0.0.1 app-api.pixiv.net，并关闭certificate validation，但不知道如何修改config（我如果在pixiv.conf后加上上一段配置就无法运行nginx），运行时显示connection reset detected。想请教一下如何解决，十分感谢！

**Comment by wzxyisme** [comment]
> 大佬您好，我修改了127.0.0.1 app-api.pixiv.net，并关闭certificate validation，但不知道如何修改config（我如果在pixiv.conf后加上上一段配置就无法运行nginx），运行时显示connection reset detected。想请教一下如何解决，十分感谢！

啥系统？

**Comment by blackhole30** [comment]
windows系统，nginx用的是mashiro的，https://github.com/mashirozx/Pixiv-Nginx。 （因为我是双系统，更希望mac能用，不过好像没有我能看得懂的教程）现状是两个系统的nginx都可以连接上，并且win的小飞机也可以运行。但挂nginx就会显示connection reset detected。
另外十分感谢大佬的工具，原来我是一张张手下的。




在 2020-05-23 19:26:57，"wzxyisme" <notifications@github.com> 写道：

大佬您好，我修改了127.0.0.1 app-api.pixiv.net，并关闭certificate validation，但不知道如何修改config（我如果在pixiv.conf后加上上一段配置就无法运行nginx），运行时显示connection reset detected。想请教一下如何解决，十分感谢！

啥系统？

**Comment by wzxyisme** [comment]
> windows系统，nginx用的是mashiro的，[https://github.com/mashirozx/Pixiv-Nginx。](https://github.com/mashirozx/Pixiv-Nginx%E3%80%82) （因为我是双系统，更希望mac能用，不过好像没有我能看得懂的教程）现状是两个系统的nginx都可以连接上，并且win的小飞机也可以运行。但挂nginx就会显示connection reset detected。 另外十分感谢大佬的工具，原来我是一张张手下的。 在 2020-05-23 19:26:57，"wzxyisme" <notifications@github.com> 写道： 大佬您好，我修改了127.0.0.1 app-api.pixiv.net，并关闭certificate validation，但不知道如何修改config（我如果在pixiv.conf后加上上一段配置就无法运行nginx），运行时显示connection reset detected。想请教一下如何解决，十分感谢！ 啥系统？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

conf > pixiv.conf 全部复制进去

`upstream www-pixiv-net { 
    #server 104.18.12.135:443;
    #server 104.18.13.135:443;
    server 210.140.131.223:443;
    server 210.140.131.225:443;
    server 210.140.131.220:443;
}

upstream account-pixiv-net { 
    server 210.140.131.226:443;
    server 210.140.131.218:443;
    server 210.140.131.222:443;
}

upstream sketch-pixiv-net { 
    server 210.140.174.37:443;
    server 210.140.170.179:443;
    server 210.140.175.130:443;
}

upstream sketch-hls-server {
    server 210.140.214.211:443;
    server 210.140.214.212:443;
    server 210.140.214.213:443;
}

upstream imgaz-pixiv-net { 
    server 210.140.131.145:443;
    server 210.140.131.144:443;
    server 210.140.131.147:443;
    server 210.140.131.153:443;
}

upstream i-pximg-net { 
    server 210.140.92.140:443;
    server 210.140.92.137:443;
    server 210.140.92.139:443;
    server 210.140.92.142:443;
    server 210.140.92.134:443;
    server 210.140.92.141:443;
    server 210.140.92.143:443;
    server 210.140.92.136:443; 
    server 210.140.92.138:443;
    server 210.140.92.144:443;
    server 210.140.92.145:443;
}

server {
    listen 80 default_server;  
    rewrite ^(.*) https://$host$1 permanent;
}

server {
    listen 443 ssl;
    server_name www.pixiv.net;

    
    ssl_certificate ca/pixiv.net.crt;
    ssl_certificate_key ca/pixiv.net.key;
    
    client_max_body_size 50M;
    
    location / {
        #proxy_ssl_server_name on;
        proxy_pass https://www-pixiv-net;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real_IP $remote_addr;
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header Accept-Encoding ''; 
        proxy_buffering off;
    }
}

server {
    listen 443 ssl;
    server_name pixiv.net;
    server_name ssl.pixiv.net;
    server_name accounts.pixiv.net;
    server_name touch.pixiv.net;
    server_name oauth.secure.pixiv.net;

    
    ssl_certificate ca/pixiv.net.crt;
    ssl_certificate_key ca/pixiv.net.key;
    
    client_max_body_size 50M;
    
    location / {
        proxy_pass https://account-pixiv-net;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real_IP $remote_addr;
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header Accept-Encoding ''; 
        proxy_buffering off;
    }
}

server {
    listen 443 ssl;
    server_name i.pximg.net;

    
    ssl_certificate ca/pixiv.net.crt;
    ssl_certificate_key ca/pixiv.net.key;
    
    location / {
        proxy_pass https://i-pximg-net;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real_IP $remote_addr;
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header Accept-Encoding ''; 
        proxy_buffering off;
    }
}

server {
    listen 443 ssl;
    server_name sketch.pixiv.net;

    
    ssl_certificate ca/pixiv.net.crt;
    ssl_certificate_key ca/pixiv.net.key;

    location / {
        proxy_pass https://sketch-pixiv-net;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real_IP $remote_addr;
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header Accept-Encoding ''; 
        proxy_buffering off;
    }
    
    # Proxying WebSockets
    location /ws/ {
        proxy_pass https://sketch-pixiv-net;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}

server {
    listen 443 ssl;
    server_name *.pixivsketch.net;

    
    ssl_certificate ca/pixiv.net.crt;
    ssl_certificate_key ca/pixiv.net.key;

    location / {
        proxy_pass https://sketch-hls-server;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real_IP $remote_addr;
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header Accept-Encoding ''; 
        proxy_buffering off;
    }
}

server {
    listen 443 ssl;
    server_name factory.pixiv.net;

    
    ssl_certificate ca/pixiv.net.crt;
    ssl_certificate_key ca/pixiv.net.key;

    location / {
        proxy_pass https://210.140.131.180/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real_IP $remote_addr;
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header Accept-Encoding ''; 
        proxy_buffering off;
    }
}

server {
    listen 443 ssl;
    server_name dic.pixiv.net;
    server_name en-dic.pixiv.net;
    server_name sensei.pixiv.net;
    server_name fanbox.pixiv.net;
    server_name payment.pixiv.net.pixiv.net;

    
    ssl_certificate ca/pixiv.net.crt;
    ssl_certificate_key ca/pixiv.net.key;
    
    location / {
        proxy_pass https://210.140.131.222/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real_IP $remote_addr;
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header Accept-Encoding ''; 
        proxy_buffering off;
    }
}

server {
    listen 443 ssl;
    server_name imgaz.pixiv.net;
    server_name comic.pixiv.net;
    server_name novel.pixiv.net;
    server_name source.pixiv.net;
    server_name i1.pixiv.net;
    server_name i2.pixiv.net;
    server_name i3.pixiv.net;
    server_name i4.pixiv.net;

    
    ssl_certificate ca/pixiv.net.crt;
    ssl_certificate_key ca/pixiv.net.key;
    
    location / {
        proxy_pass https://imgaz-pixiv-net;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real_IP $remote_addr;
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header Accept-Encoding ''; 
        proxy_buffering off;
    }
}

server {
    listen 443 ssl;
    server_name www.google.com;

    
    ssl_certificate ca/pixiv.net.crt;
    ssl_certificate_key ca/pixiv.net.key;
    
    location ^~ /recaptcha/ {
      rewrite ^(.*)$ https://www.recaptcha.net$1 break;
    }
    
    location / {
        default_type text/html;
        charset utf-8;
        return 200 'Pixiv-Nginx提醒：本工具默认代理了www.google.com，用于加载P站登陆时的验证码插件，如果你有方法正常访问www.google.com，并且不希望看到这个页面，那么将 <code>C:\Windows\System32\drivers\etc\hosts</code> 中 <code>127.0.0.1 www.google.com</code> 的那行记录删除即可。如果删除后刷新网页还是看到这个页面，请先清除一下浏览器缓存。';
    }
}

upstream app-api-pixiv-net { 
    server 210.140.131.218:443;
    server 210.140.131.223:443;
    server 210.140.131.226:443;
}

server {
    listen 443 ssl;
    server_name app-api.pixiv.net;
    
    ssl_certificate ca/pixiv.net.crt;
    ssl_certificate_key ca/pixiv.net.key;
    
    location / {
        proxy_pass https://app-api-pixiv-net;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real_IP $remote_addr;
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header Accept-Encoding ''; 
        proxy_buffering off;
    }
}

upstream wikipedia-server { 
    server 198.35.26.96:443;
    server 103.102.166.224:443;
}

server {
    listen 443 ssl;
    server_name *.wikipedia.org;
    server_name *.m.wikipedia.org;

    
    ssl_certificate ca/pixiv.net.crt;
    ssl_certificate_key ca/pixiv.net.key;
    
    location / {
        proxy_pass https://wikipedia-server/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real_IP $remote_addr;
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header Accept-Encoding ''; 
        proxy_buffering off;
    }
}

server {
    listen 443 ssl;
    server_name *.steamcommunity.com;
    server_name steamcommunity.com;

    
    ssl_certificate ca/pixiv.net.crt;
    ssl_certificate_key ca/pixiv.net.key;
    
    location / {
        proxy_pass https://23.61.176.149/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real_IP $remote_addr;
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header Accept-Encoding ''; 
        proxy_buffering off;
    }
}

server {
    listen 443 ssl;
    server_name *.steampowered.com;
    server_name steampowered.com;

    
    ssl_certificate ca/pixiv.net.crt;
    ssl_certificate_key ca/pixiv.net.key;
    
    location / {
        proxy_pass https://104.112.84.145/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real_IP $remote_addr;
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header Accept-Encoding ''; 
        proxy_buffering off;
    }
}
  server {
    listen 443 ssl;
    server_name *.archiveofourown.org;
    server_name archiveofourown.org;

    
    ssl_certificate ca/pixiv.net.crt;
    ssl_certificate_key ca/pixiv.net.key;
    
    location / {
        proxy_pass https://104.153.64.122/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real_IP $remote_addr;
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header Accept-Encoding ''; 
        proxy_buffering off;
    }
}
`

**Comment by Tsuk1ko** [comment]
@wzxyisme 要贴代码用 markdown 代码块格式，你需要解下 markdown 语法

其实也可以直接发文件的，不过需要改下扩展名

[pixiv.txt](https://github.com/Tsuk1ko/pxder/files/4671729/pixiv.txt)

@blackhole30 下下来重命名成`pixiv.conf`替换掉原本的

**Comment by blackhole30** [comment]
用conf文件替代conf文件夹中的pixiv.conf后浏览器可以访问pixiv但运行pxder还是显示connection reset detected……(已经在etc中用文本编辑器的方式把两个域名放进去了

**Comment by Tsuk1ko** [comment]
@blackhole30 nginx reload 了么

总之必须是能正常访问 https://app-api.pixiv.net/ 才算成功

**Comment by blackhole30** [comment]
無法安全連線至此網頁              
 這可能是因為網站使用過時或不安全的 TLS 安全性設定。如果這個問題持續發生，請試著連絡網站擁有人。您的 TLS 安全性設定並未設定為預設值，這也可能造成此錯誤。   
                  
会需要签名一类的吗？

**Comment by Tsuk1ko** [comment]
@blackhole30 继续前往就行，你是没按教程导入 ca 么，不过也没有影响

总之正常情况下页面内容会是一段 json

**Comment by blackhole30** [comment]
chrome安装过证书长这样：{"error":{"user_message":"\u60a8……
ie和上述一样并且不能继续前往
pxder运行结果和之前一样

**Comment by Tsuk1ko** [comment]
@blackhole30 那就说明反代到了……

那么 http://i-cf.pximg.net/ 你能正常访问么，内容是纯文本`imgaz.pixiv.net`

**Comment by blackhole30** [comment]
可以

**Comment by Tsuk1ko** [comment]
@blackhole30 那请更新一下 pxder，刚刚发布了 v2.9.2

在下载时加上`--debug`参数，将输出的错误内容发出来

**Comment by blackhole30** [comment]
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
{
    "message": "read ECONNRESET",
    "code": "ECONNRESET",
    "config": {}
}

**Comment by Tsuk1ko** [comment]
@blackhole30 麻烦再更新一下……然后步骤一样，这次应该会输出个网址

**Comment by blackhole30** [comment]
应该把步骤按标准重复过了……大概长这样
Connection reset detected.
Progress: 0https://app-api.pixiv.net/v1/user/illusts?user_id=3664310&filter=for_ios
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
{
    "message": "read ECONNRESET",
    "code": "ECONNRESET",
    "config": {}

**Comment by Tsuk1ko** [comment]
@blackhole30 那怪了，我真不知道为什么，你也试过能够访问 app-api.pixiv.net 的

唯一能想到的解释是 hosts 没对 node 生效

**Comment by blackhole30** [comment]
额我这边发现 https://app-api.pixiv.net/无法访问了orz
http://i-cf.pximg.net/ 可以访问
用得是txt转的conf，其他网址可以正常访问
应该不是pxder的问题，卸载后也无法访问

**Comment by Tsuk1ko** [comment]
@blackhole30 我准备直接在 pxder 里集成直连访问的功能，这样就不需要再弄本地反代了，等我完成后通知你

**Comment by blackhole30** [comment]
好的，不好意思麻烦了那么久……
大佬开发的功能很受用呀

**Comment by Tsuk1ko** [comment]
@blackhole30 完成了，请更新到 v2.10.0，设置中有个 Direct Mode，启用即可

**Comment by blackhole30** [comment]
虽然不明白什么原理，但可以使用了，十分感谢！

（另外不好意思请问mac端是有现成的还是需要再做？

**Comment by Tsuk1ko** [comment]
@blackhole30 直接在代码层面实现的，所有平台都可以使用

和 Pixiv-Nginx 原理一样，用了域前置技术

**Comment by blackhole30** [comment]
谢谢呀～
我装了node.js，后面好像就不行了。
等大佬有想法再更新吧。

**Comment by blackhole30** [comment]
能用就很感激了，不麻烦大佬再调试和更新了。
十分感谢！

**Comment by Tsuk1ko** [comment]
@blackhole30 mac 端也能用呀

**Comment by blackhole30** [comment]
[2020-05-24T17_29_49_361Z-debug.log](https://github.com/Tsuk1ko/pxder/files/4674069/2020-05-24T17_29_49_361Z-debug.log)
长这样，应该成功安装了node（直接安装也用brew装了一下）

**Comment by Tsuk1ko** [comment]
@blackhole30 mac 要全局安装需要`sudo`

```
sudo npm i -g pxder
```

然后输密码

**Comment by blackhole30** [comment]
等等，我用sudo权限装好了

**Comment by blackhole30** [comment]
可以用了，再一次哭出声XD
十分感谢呀！有什么我能帮得上的（打钱）叫我帮忙呀！（虽然不大用github）
祝好！

**Comment by Tsuk1ko** [comment]
@blackhole30 不用啦2333，给个⭐️就行（
