### ISSUE TITLE
在设置界面复制粘贴文件夹路径的时候按错键了，现在只要输入pxder相关指令cmd就会原地闪现并消失……

### ISSUE THREAD

**Issue by Silver-Meow** [Tsuk1ko/pxder#47]
对不起我太菜了！
setting界面复制文件夹路径按1准备粘贴的时候手抖又按倒ctrl+c了，然后弹出终止程序（选的N，虽然读过说明以后知道选不选都一样）
结果再想进设置界面的时候发现弹窗秒消失了，其他指令也一样。
重启以后状况没变，于是尝试了更新和重装……然后还是一样。
刚才清了一下windows临时文件也木大。
所以来咨询一下~

**Comment by Tsuk1ko** [comment]
删除 `C:\Users\用户名\AppData\Roaming\pxder` 文件夹后再试

**Comment by Silver-Meow** [comment]
啊！竟然是秒回，我刚看到。
现在setting可以打开了，其他的还是秒退

**Comment by Tsuk1ko** [comment]
@Silver-Meow 试试更新到最新版本以及运行时加上 --debug 参数看看是否有错误输出

**Comment by Silver-Meow** [comment]
更新了，其他指令的话窗口只会闪一下
pxder -F --debug
是这样输没错吧。

**Comment by Tsuk1ko** [comment]
@Silver-Meow 你应当在命令提示符中执行，而不是使用“运行”之类的来执行

**Comment by Silver-Meow** [comment]
原来如此，谢谢……
