### ISSUE TITLE
BUG 下载画师id 747309 的作品失败【实际情况是下载画师旧图时不会增量更新】

### ISSUE THREAD

**Issue by zyOverture** [Tsuk1ko/pxder#49]
pxder -u 747309 -M --debug 没有报错 但是只能拿到静态图，不能下载动图
![image](https://user-images.githubusercontent.com/39595404/88197182-af725600-cc74-11ea-9e55-3b0c917420f1.png)

**Comment by Tsuk1ko** [comment]
uid 747309 这个画师哪个作品是动图？我翻了十几页也全是静态图，是不是你对动图有什么误解

**Comment by Tsuk1ko** [comment]
pid 83173870 这种才是动图

**Comment by zyOverture** [comment]
82109648,78569764,78426397,78425924,78299393,78299342,77997549,76304105,75339828,75326139,75324036,74491605,74491545,74491404,73424629,73424237,72650163,72649708,72649299,72649175,72648953,72592128,72114039,71800654,71800472,71585054,71578137,71524843,70883925

虽然少还是有一些的,以前下载过

我因为把文件夹里面的压缩包都移动到其他文件夹了，重新下载这个作者的插画时，发现没有增量更新

你可以试一下，我最近发现，如果一个作者的插画很多，中间如果因为各种原因少下载了一些插画，重新下载的时候就不再继续下载这些插画了

**Comment by zyOverture** [comment]
可能不止动图有问题 我刚才又复现了一遍
uid 211254  pid 23039776 删掉后不再下载
uid 211254  pid 83109761 删掉可以下载
![批注 2020-07-25 174858](https://user-images.githubusercontent.com/39595404/88454075-55a1a400-ce9f-11ea-8ffb-33be111c1734.png)


 pid 23039776实际上是存在的
![批注 2020-07-25 174956](https://user-images.githubusercontent.com/39595404/88454077-59cdc180-ce9f-11ea-83c9-1c162211aa4d.png)

**Comment by zyOverture** [comment]
> uid 747309 这个画师哪个作品是动图？我翻了十几页也全是静态图，是不是你对动图有什么误解

**Comment by Tsuk1ko** [comment]
这是增量更新逻辑导致的，为了节约时间而设计的

https://github.com/Tsuk1ko/pxder/issues/27#issuecomment-556993033

按理来说因该不至于少下载插画，因为首先下载是从旧到新，其次下载有重试机制，只有 404 才会直接放弃下载，不太可能出现某个插画本身没问题却又重试 10 次仍无法下载的情况，详见

https://github.com/Tsuk1ko/pxder#%E8%AF%B4%E6%98%8E

**Comment by zyOverture** [comment]
> 这是增量更新逻辑导致的，为了节约时间而设计的
> 
> [#27 (comment)](https://github.com/Tsuk1ko/pxder/issues/27#issuecomment-556993033)
> 
> 按理来说因该不至于少下载插画，因为首先下载是从旧到新，其次下载有重试机制，只有 404 才会直接放弃下载，不太可能出现某个插画本身没问题却又重试 10 次仍无法下载的情况，详见
> 
> https://github.com/Tsuk1ko/pxder#%E8%AF%B4%E6%98%8E

原来是这样，有时看到命令行界面显示类似 1234/1234 这样的进度信息，但是还是没有退出，就很疑惑，这时候我会强制终止程序然后下载其他画师的作品，没想到是有图片在重试下载。其实我感觉就算对比一个画师的几万张图片id是否重复，对于现在的电脑来说也不算什么😄

**Comment by Tsuk1ko** [comment]
@zyOverture 主要是网络开销，API 只允许一次拉30张，如果画师画作很多就会很浪费时间，如果批量调会有调用频率问题

**Comment by zyOverture** [comment]
> @zyOverture 主要是网络开销，API 只允许一次拉30张，如果画师画作很多就会很浪费时间，如果批量调会有调用频率问题

https://www.pixiv.net/ajax/user/747309/profile/all?lang=zh

**Comment by Tsuk1ko** [comment]
我这里用的是移动设备客户端 API，不会有这玩意，这是网页端登录拿到的 PHP Session ID，和登录态绑定了

而且你说的这个 API 只能拿 pid 而已，并没有图链接，如果要按 pid 一个个拿那更慢了，不考虑

**Comment by zyOverture** [comment]
> 我这里用的是移动设备客户端 API，不会有这玩意，这是网页端登录拿到的 PHP Session ID，和登录态绑定了
> 
> 而且你说的这个 API 只能拿 pid 而已，并没有图链接，如果要按 pid 一个个拿那更慢了，不考虑

👌 了解了
