### ISSUE TITLE
下载出现network error问题（本人在海外）

### ISSUE THREAD

**Issue by RX78NT1FA** [Tsuk1ko/pxder#50]
![TIM图片20201005022829](https://user-images.githubusercontent.com/72353936/95022467-7b72d280-06b2-11eb-9766-13b973cb46ee.png)
debug之后显示的是这个，请问是什么问题呢。我人在日本，是我的网络有问题还是我需要重新安装。。。

**Comment by Tsuk1ko** [comment]
编辑错误中提示的这个文件`C:\Users\87774\AppData\Roaming\npm\node_modules\pxder\src\downloader.js`，找到第 209 行或者直接搜索定位也行，按下面所示修改

```diff
-	throw new Error('Incomplete download');
+	throw new Error(`Incomplete download ${dlFileSize}/${fileSize}`);
```

然后再 debug，发下截图

**Comment by aorosora** [comment]
> 编辑错误中提示的这个文件`C:\Users\87774\AppData\Roaming\npm\node_modules\pxder\src\downloader.js`，找到第 209 行或者直接搜索定位也行，按下面所示修改
> 
> ```diff
> -	throw new Error('Incomplete download');
> +	throw new Error(`Incomplete download ${dlFileSize}/${fileSize}`);
> ```
> 
> 然后再 debug，发下截图

我和他是一样的问题，下面是替换文件后的截图：
![image](https://user-images.githubusercontent.com/24385425/95044008-f539a900-0710-11eb-9729-7f371e7426be.png)
Error: Incomplete download \*\*\*\*\*\*\/undefined

**Comment by Tsuk1ko** [comment]
了解了，一会修

**Comment by Tsuk1ko** [comment]
可以更新试试了

**Comment by aorosora** [comment]
OK了，可以正常下载了
