### ISSUE TITLE
报错了，据说是pixiv开始反爬

### ISSUE THREAD

**Issue by RtYkk** [Tsuk1ko/pxder#51]
`pxder -b`和`pxder -U`都试过了，均失败。
使用clash，socks5代理。
详细信息：太长了，请移步Ubuntu Pastebin.或查看附件。看起来就是爬了整个网页……
[https://paste.ubuntu.com/p/4nzG2td8WV/](https://paste.ubuntu.com/p/4nzG2td8WV/)
[Log.txt](https://github.com/Tsuk1ko/pxder/files/5385158/Log.txt)

**Comment by lycor1s** [comment]
![image](https://user-images.githubusercontent.com/23312700/96143720-ef746c80-0f35-11eb-85e5-fecefcb15536.png)
the same situation here

**Comment by Skimige** [comment]
换了一套 client id 和 secret 能用了……（跑）；那么，初步推测是原来的被公交车 ban 了
~~不然，你甚至没法登录~~
~~这东西是不是还得自己抓一套啊（~~

**Comment by Tsuk1ko** [comment]
> 换了一套 client id 和 secret 能用了……（跑）；那么，初步推测是原来的被公交车 ban 了
> ~不然，你甚至没法登录~
> ~这东西是不是还得自己抓一套啊（~

估计还是看帐号常用地，我这里还是可以正常用的（

过会换一个 id 和 secret 吧，而且以后可能还得加一个自定义设置

**Comment by Tsuk1ko** [comment]
可以更新试试了，需要重新登陆

**Comment by DNrover** [comment]
可能和UA有关。
升级后仍无法登陆，把UA改成
`PixivIOSApp/7.9.4 (iOS 12.0.1; iPhone8,2)`
`PixivAndroidApp/5.0.155 (Android 6.0; Pixel C)`
`PixivIOSApp/7.9.4 (iOS 14.0.1; iPhone10,1)`
CLIENT_ID设置为
`KzEZED7aC0vird8jWyHM38mXjNTY`或是
`MOBrBDS8blbauoSck0ZfDbtuzpyT`都能够正常登录

**Comment by Skimige** [comment]
~~啊，总之我在我的 fork 里 fix 的时候是都改了（躺~~

**Comment by Tsuk1ko** [comment]
> ~啊，总之我在我的 fork 里 fix 的时候是都改了（躺~

害，感情是歪打正着（

**Comment by Tsuk1ko** [comment]
> 可能和UA有关。
> 升级后仍无法登陆，把UA改成
> `PixivIOSApp/7.9.4 (iOS 12.0.1; iPhone8,2)`
> `PixivAndroidApp/5.0.155 (Android 6.0; Pixel C)`
> `PixivIOSApp/7.9.4 (iOS 14.0.1; iPhone10,1)`
> CLIENT_ID设置为
> `KzEZED7aC0vird8jWyHM38mXjNTY`或是
> `MOBrBDS8blbauoSck0ZfDbtuzpyT`都能够正常登录

已安排👌

**Comment by RtYkk** [comment]
等新的release，等npm包。

**Comment by Tsuk1ko** [comment]
> 等新的release，等npm包。

已经更了

**Comment by RtYkk** [comment]
Fixed in [v2.11.3](https://github.com/Tsuk1ko/pxder/releases/tag/v2.11.3)
