### ISSUE TITLE
对于中文下载路径的支持

### ISSUE THREAD

**Issue by Skimige** [Tsuk1ko/pxder#56]
目前在尝试 pxder + Google 云端硬盘桌面版，以期减小本地存储压力

环境：Windows 10 20H2 19042.867, Windows Terminal, Powershell

目标路径：`Z:\我的云端硬盘\Pixiv`

默认代码页设置中文路径能写入配置，但是是锟斤拷，也不能正常工作；`chcp 65001` 之后设置中文路径，中文部分会被直接吃掉；此时手动向配置写入正确中文路径，程序运行时能正确识别并正常工作。

**Comment by Tsuk1ko** [comment]
v2.21.5 已修复
