### ISSUE TITLE
OAuth输入Code后卡在tokenRequest

### ISSUE THREAD

**Issue by wwc7654321** [Tsuk1ko/pxder#58]
OAuth方式登录后，输入Code后，浏览器又弹出与第一步一模一样的登录页面，再次点击登录后无反应。

代码卡在tokenRequest函数中callApi一直等待
![image](https://user-images.githubusercontent.com/8026791/129381234-eeeb22fd-6e58-488c-ae15-67bb6e83010a.png)

**Comment by Tsuk1ko** [comment]
如果你需要挂代理才能访问 pixiv，别忘了给 pxder 设置代理，或者启用直连模式

**Comment by wwc7654321** [comment]
Thanks，
确实与代理有关，https://127.0.0.1:1080 按说明替换成 socks://127.0.0.1:1080即可下载

不过 https://127.0.0.1:1080 在另一个Python脚本中却可以正常工作，有点怪 （获取到refresh_token，直接填到pxder里用了）
![image](https://user-images.githubusercontent.com/8026791/129385576-ccb01fc8-aa13-432b-9859-4a1e5bc91a0a.png)

**Comment by Tsuk1ko** [comment]
看起来你应当使用 `http://127.0.0.1:1080`，而不是 https

我猜测这段 python 中的这个代理配置实际等效的应该是

```python
proxies = {
  'http': 'http://127.0.0.1:1080',
  'https': 'http://127.0.0.1:1080'
}
```

即当请求 http / https 时分别使用这些代理，由于你没有写协议，所以默认 http

**Comment by wwc7654321** [comment]
你的意思是一个https请求可以经过http代理吗？这真是没想到，

不过仔细想想倒也没什么问题，代理只是提供一个二进制通道

**Comment by Tsuk1ko** [comment]
当然是可以的，而且一般代理软件在本地提供的都是 http 和 socks
