### ISSUE TITLE
I can't connect to the pixiv server using the command window

### ISSUE THREAD

**Issue by zkj2716491** [Tsuk1ko/pxder#63]
RETRY https://oauth.secure.pixiv.net/auth/token
connect ETIMEDOUT 104.244.43.57:443
RETRY https://oauth.secure.pixiv.net/auth/token
connect ETIMEDOUT 104.244.43.57:443

Login fail! Please check your input or proxy setting.

**Comment by LingLyehUn** [comment]
我也是同样的问题，正在用其他设备尝试

**Comment by lovezzzxxx** [comment]
可能需要先在`pxder --setting`里设置代理
