### ISSUE TITLE
(Feature Request) An online version of Pxder

### ISSUE THREAD

**Issue by pyramidjack** [Tsuk1ko/pxder#64]
Hey. Ya think you can make an online version of Pxder similar to Furarchiver?: https://furarchiver.net/

The main reason why I'm asking this is because there's literally no Archiver Site that downloads entire galleries from Pixiv. Perhaps you could do some actual justice by creating an online version of Pxder similar to Furarchiver?

**Comment by Tsuk1ko** [comment]
Sorry, there are currently no plans to develop new features.
