### ISSUE TITLE
no worket

### ISSUE THREAD

**Issue by MiTereKun** [Tsuk1ko/pxder#66]
It seemed to me that it stopped working a long time ago, but it turns out back in early April everything was ok.
Please check and check the possibilities, thanks.

Right now, a constant cyclical attempt to download the same picture. In some cases, it is not possible to download even the first picture and the folder with the authors does not even appear in the selected directory

**Comment by Tsuk1ko** [comment]
I tested, it work properly.

What node version you are using and did you enable direct mode or porxy?
