### ISSUE TITLE
在直连和代理情况下都无法使用了

### ISSUE THREAD

**Issue by coltaime** [Tsuk1ko/pxder#67]
上个月还没问题，今天试了下。不管是直连模式还是走代理，都会反复出现Network error! Pause 5 minutes，一张图片都下载不了。
-f不会产生新关注的文件夹，反复Network error。-u检测到新的进行下载时，也一样。一张都下不了提示Network error。
尝试使用pxder --debug输出，提示Missing arguments。
已使用npm i -g pxder更新至最新版本。
已尝试使用不同的代理节点，已尝试重新登录。

**Comment by Tsuk1ko** [comment]
--debug 参数加到你正常使用的指令后面，pxder -u xxx --debug

你的 node 版本是多少

**Comment by Tsuk1ko** [comment]
已修复，尝试 v2.12.8
