### ISSUE TITLE
无法正确处理 😂 emoji 文件名

### ISSUE THREAD

**Issue by Simakeng** [Tsuk1ko/pxder#69]
行为类似 #14 
![image](https://github.com/Tsuk1ko/pxder/assets/20399522/2bd4574d-10b8-4896-93b3-845ecaac91ce)

系统：Windows 10 22H2 19045.3448

```bash
>node --version
v20.5.1
>pxder --version
2.12.8
```
NTFS 是可以处理这个文件名的
![image](https://github.com/Tsuk1ko/pxder/assets/20399522/474d9b14-3527-4dac-8d0c-769cd3ec384b)

![image](https://github.com/Tsuk1ko/pxder/assets/20399522/e4ed8174-a7c6-43ca-ace9-caa9b33269ae)

**Comment by Tsuk1ko** [comment]
应该是 node 20 的 bug

https://github.com/nodejs/node/issues/48673

可以先降级到 16 或者 18
