### ISSUE TITLE
已知画师删号的情况下，可否设置规则绕过该画师继续执行其他画师的更新？

### ISSUE THREAD

**Issue by isuzukuma** [Tsuk1ko/pxder#70]
![image](https://github.com/Tsuk1ko/pxder/assets/80672853/85a492ab-c9a8-4970-867e-96097cdd4f08)
如图，在使用pxder -U的时候，运行到报错的画师，然后通过uid查找该画师已经删号了，程序报错之后直接停止，不会更新后续画师，能否自定义规则绕过这些报错的画师？

**Comment by Tsuk1ko** [comment]
修复了，这个停止是个bug，原本的设计就是可以继续下载其他画师
