### ISSUE TITLE
做了 AUR 的支持

### ISSUE THREAD

**Issue by VergeDX** [Tsuk1ko/pxder#9]
https://aur.archlinux.org/pkgbase/nodejs-pxder/  

顺便，新年好_(:з」∠)_

**Comment by Tsuk1ko** [comment]
天了噜！
新年好 (\*ﾟ∀ﾟ\*)

**Comment by VergeDX** [comment]
用 [npm2PKGBUILD]( https://github.com/Filirom1/npm2arch ) 转换而来  
一开始是想自己写的，折腾了半天也没弄好  
推到 AUR 的时候又研究了半天_(:з」∠)_
